use_frameworks!

target 'RouterManager_Example' do
  pod 'RouterManager', :path => '../'

  target 'RouterManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
